### ISSUE TITLE
BUG: Create new drawing does not work

### ISSUE THREAD

**Issue by ShravanSunder** [zsviczian/obsidian-excalidraw-plugin#1044]
**Your environment**
Please run `Command Palette/Show Debug info` in Obsidian and paste the result here.
SYSTEM INFO:
	Obsidian version: v1.1.16
	Installer version: v0.15.9
	Operating system: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 22.3.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.3.2
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 73
	Plugins enabled: 57
		1: Auto Link Title v1.4.1
		2: Auto Note Mover v1.2.0
		3: Checklist v2.2.12
		4: Commander v0.4.9
		5: Copy Block Link v1.0.4
		6: Creases v0.6.6
		7: Dataview v0.5.55
		8: Editor Syntax Highlight v0.1.3
		9: File path to URI v1.4.1
		10: Find and replace in selection v1.0.1
		11: Hotkeys for starred files and searches v0.0.4
		12: Icon Folder v1.6.0
		13: Todoist Plugin v1.10.1
		14: Templater v1.16.0
		15: Style Settings v1.0.3
		16: Simple Embeds v1.14.1
		17: Kanban v1.5.2
		18: Linter v1.10.3
		19: Map of Content v0.1.18
		20: Media Extended v2.11.1
		21: Minimal Theme Settings v6.3.1
		22: Natural Language Dates v0.6.1
		23: Omnisearch v1.12.3
		24: Obsidian Git v2.17.0
		25: Paste URL into selection v1.7.0
		26: QuickAdd v0.11.6
		27: Readwise Official v2.0.1
		28: Recent Files v1.3.5
		29: Rich Links v1.1.0
		30: Note Refactor v1.7.1
		31: Ozan's Image in Editor Plugin v2.1.9
		32: Tag Wrangler v0.5.6
		33: Text Generator v0.2.6
		34: DB Folder v3.3.2
		35: Global Hotkeys v0.1.2
		36: Copy Search URL v1.1.0
		37: Dynamic Highlights v0.3.1
		38: Hotkey Helper v0.3.15
		39: Periodic Notes v0.0.17
		40: Map View v3.0.1
		41: Link Nodes In Canvas v0.0.5
		42: Footnote Shortcut v0.0.9
		43: Another Quick Switcher v8.6.1
		44: Text Extractor v0.4.2
		45: CustomJS v1.0.13
		46: Janitor v1.0.7
		47: Homepage v2.8
		48: Image Toolkit v1.3.1
		49: Link Exploder v0.2.4
		50: Completr v3.1.3
		51: Various Complements v8.0.0
		52: Tag & Word Cloud v1.3.2
		53: ExcaliBrain v0.1.11
		54: List Callouts v1.1.4
		55: Mindmap NextGen v1.6.5
		56: Chronology v1.1.4
		57: Excalidraw v1.8.17

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**

Cannot create new excalidraw files.   I can open old files.  When running command, it only opens new tab.  It doens't work from context menu in file explorer either

**To Reproduce**

**Expected behavior**
Excalidraw files can be created.

**Screenshots**

**Additional context**

**Comment by ShravanSunder** [comment]
i'm getting these in the dev console

```
app.js:1 Uncaught (in promise) Error: File already exists.
    at t.<anonymous> (app.js:1:1124612)
    at app.js:1:235836
    at Object.next (app.js:1:235941)
    at a (app.js:1:234680)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
await in a (async)
eval @ plugin:obsidian-excalidraw-plugin:19
e.handleEvent @ app.js:1
click @ app.js:1
apply @ /Applications/Obsidian.app/Contents/Resources/app.asar/node_modules/@electron/remote/dist/src/renderer/callbacks-registry.js:54
(anonymous) @ /Applications/Obsidian.app/Contents/Resources/app.asar/node_modules/@electron/remote/dist/src/renderer/remote.js:345
(anonymous) @ /Applications/Obsidian.app/Contents/Resources/app.asar/node_modules/@electron/remote/dist/src/renderer/remote.js:327
emit @ node:events:390
onMessage @ node:electron/js2c/renderer_init:69
app.js:1 Uncaught (in promise) Error: File already exists.
    at t.<anonymous> (app.js:1:1124612)
    at app.js:1:235836
    at Object.next (app.js:1:235941)
    at a (app.js:1:234680)
```

**Comment by ShravanSunder** [comment]
HI @zsviczian !  I've disabled those plugins and it has the same issue.

Here are my settings

<img width="873" alt="2023-03-04 0315 Obsidian academy 05-06 My investment system - shravan-pkm - Obsidian v1 1 16" src="https://user-images.githubusercontent.com/5294949/222924719-39878520-92ed-4c87-bb07-428b02e8c994.png">

<img width="839" alt="2023-03-04 0315 Obsidian academy 05-06 My investment system - shravan-pkm - Obsidian v1 1 16" src="https://user-images.githubusercontent.com/5294949/222924720-af8bd052-fd37-40ca-ad5a-06dc9fe22051.png">


<img width="873" alt="2023-03-04 0315 Obsidian academy 05-06 My investment system - shravan-pkm - Obsidian v1 1 16" src="https://user-images.githubusercontent.com/5294949/222924723-2d405915-ab3d-49eb-83ef-1b4adcc52141.png">

**Comment by ShravanSunder** [comment]
@zsviczian  I figured it out.  its the filename prefix.  I think i didn't update for a while, and we didn't need a prefix before or something.  That's the reason!  

thanks for the help!  and the great extension!  🙏🏽
