### ISSUE TITLE
BUG: Excalidraw Automate addLatex seems to be broken?

### ISSUE THREAD

**Issue by half-adder** [zsviczian/obsidian-excalidraw-plugin#1472]
**Your environment**

```
SYSTEM INFO:
	Obsidian version: v1.5.0
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64 21.6.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 31
	Plugins enabled: 26
		1: Dataview v0.5.64
		2: Excel to Markdown Table v0.4.0
		3: Natural Language Dates v0.6.1
		4: Tasks v5.1.1
		5: Templater v1.18.1
		6: Advanced Tables v0.19.1
		7: Recent Files v1.3.8
		8: QuickAdd v1.6.0
		9: Paste image rename v1.6.1
		10: Contextual Typography v2.2.5
		11: Remember cursor position v1.0.8
		12: Calendar v1.5.10
		13: Highlightr v1.2.2
		14: Image Toolkit v1.4.1
		15: Advanced Paste v1.0.0
		16: Outliner v4.8.0
		17: Zotero Integration v3.0.12
		18: Text Extractor v0.4.8
		19: Excalidraw v2.0.3
		20: Periodic Notes v0.0.17
		21: Rollover Daily Todos v1.1.7
		22: Supercharged Links v0.11.1
		23: Linter v1.20.1
		24: Style Settings v1.0.7
		25: Minimal Theme Settings v7.3.0
		26: Latex Suite v1.8.9

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

**Describe the bug**

Excalidraw automate does not seem to be able to add latex formulas correctly.

**To Reproduce**
1. Create template with the following content:

```
<%*
const ea = ExcalidrawAutomate;
ea.reset();

ea.addLaTex(-100,70, '$$\frac{A}{B}$$');

await ea.create({onNewPane: true});
%>
```

> Note, I have also tried this using `'$\frac{A}{B}$'` and `'\frac{A}{B}'`

2. Run the template using `Templater: Open insert template modal`

3. Obsidian opens new Excalidraw pane, but it is empty. 

An error message appears which reads `Unknown error loading LaTeX. Using fallback solution. Try closing and reopening this drawing.`

Inspecting the console log, I get the following error message:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading '4')
    at Object.v [as item] (tex-chtml-full.js:1:304798)
    at t.parse (tex-chtml-full.js:1:220328)
    at t.parse (tex-chtml-full.js:1:265869)
    at t.Parse (tex-chtml-full.js:1:266477)
    at new t (tex-chtml-full.js:1:265210)
    at e.compile (tex-chtml-full.js:1:203152)
    at t.compile (tex-chtml-full.js:1:49304)
    at Object.renderMath (tex-chtml-full.js:1:39300)
    at e.renderConvert (tex-chtml-full.js:1:40113)
    at t.convert (tex-chtml-full.js:1:49191)
    at t.convert (tex-chtml-full.js:1:43226)
    at e.MathJax.<computed> [as tex2chtml] (tex-chtml-full.js:1:26549)
    at mathjaxImage2html (plugin:obsidian-excalidraw-plugin:21:199942)
    at tex2dataURL (plugin:obsidian-excalidraw-plugin:21:199410)
    at async ExcalidrawAutomate.addLaTex (plugin:obsidian-excalidraw-plugin:79:90432)
```

**Expected behavior**
I would expect Obsidian open a new Excalidraw drawing with a LaTeX object as specified.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by half-adder** [comment]
The reason I'm doing this is I'd like to use the Excalidraw Automate Mindmap / Family Tree examples, but use LaTeX formulas in the markdown lists instead of plaintext, e.g.: 

```
- $$\frac{\text{C}}{\text{D}}$$
	- $$\frac{\text{A}}{\text{B}}$$
- $$\frac{\text{E}}{\text{F}}$$
	- $$\frac{\text{G}}{\text{H}}$$
	- $$\frac{\text{I}}{\text{J}}$$
```

**Comment by zsviczian** [comment]
It works. You need to await addLaTex.
